# Generated by Django 5.1.7 on 2026-02-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoilEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(choices=[('Karthikeyan', 'Karthikeyan'), ('Thinakaran', 'Thinakaran'), ('Jagan', 'Jagan'), ('Sundar', 'Sundar')], max_length=100)),
                ('coil_no', models.CharField(max_length=100)),
                ('source', models.CharField(choices=[('JSW', 'JSW'), ('TATA', 'TATA'), ('HYUN', 'HYUN'), ('AMNS', 'AMNS')], max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('ok_count', models.IntegerField()),
                ('hold_count', models.IntegerField()),
                ('rejection_count', models.IntegerField()),
                ('diagonal_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
